apiVersion: v1 
kind: Pod
metadata:
  name: foo-pod
  namespace: default
spec:
  containers:
  - name: foo-pod
    image: nginx:1.14.2
    volumeMounts: 
    - mountPath: /mnt
      name: hostfs
  volumes:
  - name: hostfs
    hostPath:  
      path: /
  automountServiceAccountToken: true
  hostNetwork: true
